### ISSUE TITLE
BCC gets removed

### ISSUE THREAD

**Issue by JanvadeHe** [cyb3rmonk/reply-all-auto-cc#1]
Great extension, but I encounter two issues that make it hard for me to use. Here is the first.
I have an automatic BCC to myself whenever I sent an email, so that everything I sent is included in my Inbox timeline. Unfortunately, reply-all-auto-cc removes that BCC.
Hope this can be solved.
Thanks.

Best, Jan

**Comment by cxshen** [comment]
Yes, I have the same issue which prevent me from using this nice addon.

**Comment by cyb3rmonk** [comment]
FIXED - however, the fix required me to compensate for a weird quirk of Thunderbird's add-on api so I'm not sure if it will work in all cases. Please let me know if you still have the problem.
