### ISSUE TITLE
all email addresses gone when edit again from draft folder

### ISSUE THREAD

**Issue by JanvadeHe** [cyb3rmonk/reply-all-auto-cc#2]
Great extension, but I encounter two issues that make it hard for me to use. Here is the second.
I regularly save half-written emails in the TB draft folder. Unfortunately, when reply-all-auto-cc is active and I start working on a draft email again (by clicking on "Edit" in the draft folder) all email addresses in the draft (in To, CC, BCC) are gone.
Hope this can be solved.
Thanks.

Best, Jan

**Comment by cyb3rmonk** [comment]
Thanks for reporting this. My schedule is finally clearing up a little, so I will look at this in the next few days and either publish fix or report back.

**Comment by cyb3rmonk** [comment]
FIXED - however, the fix required me to compensate for a weird quirk of Thunderbird's add-on api so I'm not sure if it will work in all cases. Please let me know if you still have the problem.
