### ISSUE TITLE
`mailto:` links not working.

### ISSUE THREAD

**Issue by Kamilcuk** [cyb3rmonk/reply-all-auto-cc#3]
When doing from terminal:

     thunderbird -compose "to=email@address.com"

The email address, like, very quickly flashes in `To:` field and then just disappears - thunderbird just opens a compose window with an empty `To:` address. When disabling the extension, it works fine, and the command opens a compose window with filled `To` field with the email address.

Because of that, the `mailto:` HTTP links do not work, as they open just an empty compose window.

**Comment by cyb3rmonk** [comment]
FIXED - however, the fix required me to compensate for a weird quirk of Thunderbird's add-on api so I'm not sure if it will work in all cases. Please let me know if you still have the problem.
